on:
  push:
      - name: HTML to PDF
        uses: fifsky/html-to-pdf-action@v0.1.0
              with:
                htmlFile: ./index.html
                outputFile: ./CVEdwardSinghBhomrah.pdf
          
