name: HTML to PDF Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ././index.html
          outputFile: /CV-EdwardSB.pdf
          pdfOptions: |
            {
              "format": "A4",
              "margin": {
                "top": "10mm",
                "left": "10mm",
                "right": "10mm",
                "bottom": "10mm"
              }
            }
