name: Test Build Pdf

on: [push, pull_request]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  html_to_pdf:
    name: Generate PDF
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: cv/index.html
          outputFile: ./generated/cv.pdf
          pdfOptions: '{"margin": {"top": "1px", "left": "100px", "right": "100px", "bottom": "100px"}}'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Example PDF
          path: ./generated